name: Enviar para a vps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Enviar os ficheiros via ssh
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: david
          PORT: 22
          KEY: ${{ secrets.KEY }}
        with:
          source: "."
          target: "/home/david/danittobot"
