name: Enviar para a vps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Enviar os ficheiros via ssh para a vps
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: david
          PORT: 22
          KEY: ${{ secrets.KEY }}
        with:
          source: "."
          target: "/home/david/danittobot"
  updateDani:
    name: Build and re-run danitto
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: david
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          echo "Entrando no dirétorio"
          cd danittobot
          echo "Buildando o bot"
          docker build -t danitto .
          echo "Desligando o processo anterior"
          docker rm danitto
          echo "Ligando o Danitto"
          docker run -d --name danitto danitto

     
