name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository to vps
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ubuntu
        PORT: 22
        KEY: ${{ secrets.KEY }}
      with:
        source: "."
        target: "/home/ubuntu/danittobot"
