name: atualizar danitto
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: david
        key: ${{ secrets.KEY }}
        port: 22
        script: |
           tmux send-keys -t dani C-c
           tmux send -t dani "sudo bash /home/david/atualizarDanitto.sh" ENTER
